version: '3.8'

services:
  db:
    image: postgres:15
    container_name: kahve_postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=sifre123
      - POSTGRES_DB=KahveDb
    ports:
      - "5432:5432"
    volumes:
      - kahve_data:/var/lib/postgresql/data

volumes:
  kahve_data: